import type { ObjectDefinition, ObjectFieldDefinition, ObjectMetadataSourceRef, ObjectRegistryEntry } from './types'

const opportunityLifecycleSource: ObjectMetadataSourceRef = {
  domain: 'OpportunityLifecycle',
  exportName: 'getOpportunityMetadata',
}

const opportunityValidationSource: ObjectMetadataSourceRef = {
  domain: 'OpportunityLifecycle',
  exportName: 'validateOpportunity',
}

const tenantRequirementSource: ObjectMetadataSourceRef = {
  domain: 'TenantRequirement',
  exportName: 'requirementAColumns/requirementBColumns/requirementCColumns',
}

const opportunityFields: ObjectFieldDefinition[] = [
  {
    key: 'opportunityId',
    label: 'Opportunity (name and ID)',
    type: 'text',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'opportunityId' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'opportunityName',
    label: 'Opportunity name',
    type: 'text',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'opportunityName' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'stage',
    label: 'Stage',
    type: 'picklist',
    section: 'header',
    editable: true,
    source: { domain: 'OpportunityLifecycle', exportName: 'validateOpportunityTransition', fieldKey: 'stage' },
    validationSource: { domain: 'OpportunityLifecycle', exportName: 'validateOpportunityTransition' },
  },
  {
    key: 'type',
    label: 'Opportunity Type',
    type: 'picklist',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'type' },
    picklistSource: { domain: 'OpportunityLifecycle', exportName: 'OPPORTUNITY_SUB_TYPE_OPTIONS', fieldKey: 'type' },
  },
  {
    key: 'subType',
    label: 'Opportunity sub type',
    type: 'picklist',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'subType' },
    picklistSource: { domain: 'OpportunityLifecycle', exportName: 'OPPORTUNITY_SUB_TYPE_OPTIONS', fieldKey: 'subType' },
  },
  {
    key: 'accountId',
    label: 'Account (end user)',
    type: 'reference',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'accountId' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'salesManagerId',
    label: 'Deal Owner',
    type: 'reference',
    section: 'header',
    editable: true,
    source: { ...opportunityLifecycleSource, fieldKey: 'salesManagerId' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'deliveryDate',
    label: 'Delivery date',
    type: 'date',
    section: 'header',
    editable: true,
    visible: { ...opportunityLifecycleSource, rule: 'visible', fieldKey: 'deliveryDate' },
    source: { ...opportunityLifecycleSource, fieldKey: 'deliveryDate' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'pocStartDate',
    label: 'Start Date',
    type: 'date',
    section: 'header',
    editable: true,
    visible: { ...opportunityLifecycleSource, rule: 'visible', fieldKey: 'pocStartDate' },
    source: { ...opportunityLifecycleSource, fieldKey: 'pocStartDate' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'pocEndDate',
    label: 'End Date',
    type: 'date',
    section: 'header',
    editable: true,
    visible: { ...opportunityLifecycleSource, rule: 'visible', fieldKey: 'pocEndDate' },
    source: { ...opportunityLifecycleSource, fieldKey: 'pocEndDate' },
    validationSource: opportunityValidationSource,
  },
  {
    key: 'warrantyServiceMonths',
    label: 'Warranty/Service period (months)',
    type: 'integer',
    section: 'header',
    editable: true,
    visible: { ...opportunityLifecycleSource, rule: 'visible', fieldKey: 'warrantyServiceMonths' },
    source: { ...opportunityLifecycleSource, fieldKey: 'warrantyServiceMonths' },
  },
  {
    key: 'tenantRequirements',
    label: 'Tenant requirements',
    type: 'collection',
    tab: 'requirements',
    editable: true,
    source: tenantRequirementSource,
    validationSource: { domain: 'TenantRequirement', exportName: 'validateRequirementA/validateRequirementB/validateRequirementC' },
  },
  {
    key: 'engagementCircles',
    label: 'Engagement Circle',
    type: 'collection',
    tab: 'engagementCircles',
    editable: true,
    source: { domain: 'EngagementCircle', exportName: 'ENGAGEMENT_ROLE_OPTIONS' },
  },
]

export const OPPORTUNITY_OBJECT_DEFINITION: ObjectDefinition = {
  key: 'opportunity',
  label: 'Opportunity',
  pluralLabel: 'Opportunities',
  identityField: 'opportunityId',
  source: opportunityLifecycleSource,
  fields: opportunityFields,
  sections: [{ id: 'header', label: 'Header', source: opportunityLifecycleSource }],
  tabs: [
    { id: 'requirements', label: 'Tenant Requirements', source: tenantRequirementSource },
    { id: 'engagementCircles', label: 'Engagement Circle', source: { domain: 'EngagementCircle', exportName: 'ENGAGEMENT_ROLE_OPTIONS' } },
    { id: 'documents', label: 'Documents', source: { domain: 'DocumentCollection' } },
  ],
  relationships: [
    { relationship: 'composes', domain: 'TenantRequirement', exportName: 'requirementAColumns/requirementBColumns/requirementCColumns' },
    { relationship: 'composes', domain: 'EngagementCircle', exportName: 'ENGAGEMENT_ROLE_OPTIONS' },
    { relationship: 'composes', domain: 'DocumentCollection' },
    { relationship: 'projects', domain: 'ProjectLifecycle', description: 'Created Project read models consume Opportunity-created Project links.' },
  ],
}

const projectLifecycleSource: ObjectMetadataSourceRef = {
  domain: 'ProjectLifecycle',
  exportName: 'getProjectFormMetadata',
}

const projectFields: ObjectFieldDefinition[] = [
  {
    key: 'pid',
    label: 'PID#',
    type: 'readonly',
    section: 'header',
    editable: false,
    source: { ...projectLifecycleSource, fieldKey: 'pid' },
  },
  {
    key: 'opportunityName',
    label: 'Project name',
    type: 'text',
    section: 'header',
    editable: true,
    source: { ...projectLifecycleSource, fieldKey: 'opportunityName' },
    validationSource: { domain: 'ProjectLifecycle', exportName: 'validateProjectSave' },
  },
  {
    key: 'opportunityId',
    label: 'Opportunity (name and ID)',
    type: 'reference',
    section: 'header',
    editable: true,
    source: { ...projectLifecycleSource, fieldKey: 'opportunityId' },
    readModelSource: { domain: 'OpportunityLifecycle', exportName: 'linkedOpportunityForProject' },
  },
  {
    key: 'mainType',
    label: 'Project Type',
    type: 'readonly',
    section: 'header',
    editable: false,
    source: { ...projectLifecycleSource, fieldKey: 'mainType' },
    readModelSource: { domain: 'OpportunityLifecycle', exportName: 'projectTypeForOpportunity' },
  },
  {
    key: 'subType',
    label: 'Project sub type',
    type: 'readonly',
    section: 'header',
    editable: false,
    source: { ...projectLifecycleSource, fieldKey: 'subType' },
    readModelSource: { domain: 'OpportunityLifecycle', exportName: 'projectTypeForOpportunity' },
  },
  {
    key: 'deliveryDate',
    label: 'Delivery date',
    type: 'date',
    section: 'header',
    editable: true,
    source: { ...projectLifecycleSource, fieldKey: 'deliveryDate' },
  },
  {
    key: 'progressStatus',
    label: 'Project status',
    type: 'readonly',
    section: 'header',
    editable: false,
    source: { ...projectLifecycleSource, fieldKey: 'progressStatus' },
    readModelSource: { domain: 'ProjectLifecycle', exportName: 'projectStatusLabel' },
  },
  {
    key: 'currentMilestone',
    label: 'Current Milestone',
    type: 'readonly',
    section: 'header',
    editable: false,
    source: { ...projectLifecycleSource, fieldKey: 'currentMilestone' },
    readModelSource: { domain: 'ProjectLifecycle', exportName: 'projectDashboardCurrentMilestone' },
  },
  {
    key: 'lastMilestone',
    label: 'Last Milestone',
    type: 'readonly',
    section: 'dashboard',
    editable: false,
    source: { domain: 'ProjectLifecycle', exportName: 'projectDashboardLastMilestone', fieldKey: 'lastMilestone' },
    readModelSource: { domain: 'MilestonePlan', exportName: 'deriveProjectProgress' },
  },
  {
    key: 'percent',
    label: '%',
    type: 'readonly',
    section: 'dashboard',
    editable: false,
    source: { domain: 'ProjectLifecycle', exportName: 'projectDashboardPercent', fieldKey: 'percent' },
    readModelSource: { domain: 'MilestonePlan', exportName: 'deriveProjectProgress' },
  },
  {
    key: 'tenantRequirements',
    label: 'Tenant Requirements',
    type: 'collection',
    tab: 'tenantRequirements',
    editable: false,
    source: { domain: 'ProjectLifecycle', exportName: 'completeProjectRequirementSections' },
    readModelSource: { domain: 'TenantRequirement', exportName: 'requirementAColumns/requirementBColumns/requirementCColumns' },
  },
  {
    key: 'projectSystems',
    label: 'Systems',
    type: 'collection',
    tab: 'systemsTenants',
    editable: true,
    source: { domain: 'ProjectLifecycle', exportName: 'linkedSystemsForProject' },
    readModelSource: { domain: 'AllocationContext', exportName: 'activeProjectSystemLinks' },
    validationSource: { domain: 'AllocationContext', exportName: 'validateProductionAllocation/validateReusedInternalAllocation/validateExistingSystemLink' },
  },
  {
    key: 'projectTenants',
    label: 'Tenants',
    type: 'collection',
    tab: 'systemsTenants',
    editable: false,
    source: { domain: 'ProjectLifecycle', exportName: 'linkedTenantsForProject' },
    readModelSource: { domain: 'AllocationContext', exportName: 'activeProjectTenantLinks' },
  },
]

export const PROJECT_OBJECT_DEFINITION: ObjectDefinition = {
  key: 'project',
  label: 'Project',
  pluralLabel: 'Projects',
  identityField: 'pid',
  source: projectLifecycleSource,
  fields: projectFields,
  sections: [
    { id: 'header', label: 'Header', source: projectLifecycleSource },
    { id: 'dashboard', label: 'Dashboard', source: { domain: 'ProjectLifecycle', exportName: 'projectDashboardPercent' } },
  ],
  tabs: [
    { id: 'tenantRequirements', label: 'Tenant Requirements', source: { domain: 'ProjectLifecycle', exportName: 'completeProjectRequirementSections' } },
    { id: 'milestones', label: 'Milestones', source: { domain: 'MilestonePlan', exportName: 'orderedProjectMilestones' } },
    { id: 'tasks', label: 'Tasks', source: { domain: 'MilestonePlan', exportName: 'orderedProjectTasks' } },
    { id: 'systemsTenants', label: 'Systems and Tenants', source: { domain: 'AllocationContext', exportName: 'activeProjectSystemLinks/activeProjectTenantLinks' } },
    { id: 'engagementCircles', label: 'Engagement Circle', source: { domain: 'EngagementCircle', exportName: 'ENGAGEMENT_ROLE_OPTIONS' } },
    { id: 'documents', label: 'Documents', source: { domain: 'DocumentCollection' } },
  ],
  relationships: [
    { relationship: 'references', domain: 'OpportunityLifecycle', exportName: 'linkedOpportunityForProject' },
    { relationship: 'composes', domain: 'TenantRequirement', exportName: 'requirementAColumns/requirementBColumns/requirementCColumns' },
    { relationship: 'composes', domain: 'MilestonePlan', exportName: 'deriveProjectProgress' },
    { relationship: 'composes', domain: 'AllocationContext', exportName: 'activeProjectSystemLinks/activeProjectTenantLinks' },
    { relationship: 'composes', domain: 'EngagementCircle', exportName: 'ENGAGEMENT_ROLE_OPTIONS' },
    { relationship: 'composes', domain: 'DocumentCollection' },
  ],
}

const systemInventorySource: ObjectMetadataSourceRef = {
  domain: 'SystemInventory',
  exportName: 'getSystemInventoryMetadata',
}

const hostingContextSource: ObjectMetadataSourceRef = {
  domain: 'HostingContext',
  exportName: 'DEFAULT_HOSTING_CONTEXT',
}

const systemFields: ObjectFieldDefinition[] = [
  {
    key: 'sid',
    label: 'SID',
    type: 'readonly',
    section: 'identity',
    editable: false,
    source: { ...systemInventorySource, fieldKey: 'sid' },
  },
  {
    key: 'machineId',
    label: 'MID',
    type: 'text',
    section: 'identity',
    editable: true,
    source: { ...systemInventorySource, fieldKey: 'machineId' },
  },
  {
    key: 'systemClass',
    label: 'System Class',
    type: 'readonly',
    section: 'inventory',
    editable: false,
    source: { domain: 'SystemInventory', exportName: 'SYSTEM_CLASS_CUSTOMER/SYSTEM_CLASS_POC_DEMO_TRAINING', fieldKey: 'systemClass' },
  },
  {
    key: 'purpose',
    label: 'Purpose',
    type: 'picklist',
    section: 'inventory',
    editable: true,
    source: { ...systemInventorySource, fieldKey: 'purpose' },
    picklistSource: { domain: 'SystemInventory', exportName: 'REUSED_PURPOSE_OPTIONS', fieldKey: 'purpose' },
  },
  {
    key: 'availability',
    label: 'Availability Status',
    type: 'picklist',
    section: 'inventory',
    editable: true,
    source: { ...systemInventorySource, fieldKey: 'availability' },
    picklistSource: { domain: 'SystemInventory', exportName: 'REUSED_STATUS_OPTIONS', fieldKey: 'availability' },
  },
  {
    key: 'operationalStatus',
    label: 'Operational Status',
    type: 'picklist',
    section: 'inventory',
    editable: true,
    source: { ...systemInventorySource, fieldKey: 'operationalStatus' },
    picklistSource: { domain: 'SystemInventory', exportName: 'PRODUCTION_OPERATIONAL_STATUS_OPTIONS/REUSED_OPERATIONAL_STATUS_OPTIONS', fieldKey: 'operationalStatus' },
  },
  {
    key: 'productType',
    label: 'Product',
    type: 'picklist',
    section: 'configuration',
    editable: true,
    source: { domain: 'ApplicationConfiguration', exportName: 'APPLICATION_CONFIGURATION_FIELDS', fieldKey: 'productType' },
    validationSource: { domain: 'ApplicationConfiguration', exportName: 'validateApplicationConfiguration' },
  },
  {
    key: 'hostingType',
    label: 'Hosting',
    type: 'picklist',
    section: 'hosting',
    editable: true,
    source: { ...hostingContextSource, fieldKey: 'hostingType' },
    picklistSource: { domain: 'HostingContext', exportName: 'HOSTING_OPTIONS', fieldKey: 'hostingType' },
    validationSource: { domain: 'HostingContext', exportName: 'validateHostingContext' },
  },
  {
    key: 'cloudPlatform',
    label: 'Cloud Platform',
    type: 'picklist',
    section: 'hosting',
    editable: true,
    source: { ...hostingContextSource, fieldKey: 'cloudPlatform' },
    picklistSource: { domain: 'HostingContext', exportName: 'CLOUD_PLATFORM_OPTIONS', fieldKey: 'cloudPlatform' },
    validationSource: { domain: 'HostingContext', exportName: 'validateHostingContext' },
  },
  {
    key: 'csp',
    label: 'CSP',
    type: 'picklist',
    section: 'hosting',
    editable: true,
    source: { ...hostingContextSource, fieldKey: 'csp' },
    picklistSource: { domain: 'HostingContext', exportName: 'cspOptionsForPlatform', fieldKey: 'csp' },
  },
  {
    key: 'cloudRegion',
    label: 'Region',
    type: 'picklist',
    section: 'hosting',
    editable: true,
    source: { ...hostingContextSource, fieldKey: 'cloudRegion' },
    picklistSource: { domain: 'HostingContext', exportName: 'regionOptionsForPlatform', fieldKey: 'cloudRegion' },
  },
  {
    key: 'url',
    label: 'URL',
    type: 'text',
    section: 'hosting',
    editable: true,
    source: { ...hostingContextSource, fieldKey: 'url' },
  },
  {
    key: 'tenantIds',
    label: 'Tenants',
    type: 'collection',
    tab: 'tenant',
    editable: false,
    source: { domain: 'SystemInventory', exportName: 'systemReadModel', fieldKey: 'tenantIds' },
  },
  {
    key: 'linkedProjectIds',
    label: 'Linked Projects',
    type: 'collection',
    tab: 'tenant',
    editable: false,
    source: { domain: 'SystemInventory', exportName: 'systemReadModel', fieldKey: 'linkedProjectIds' },
    readModelSource: { domain: 'AllocationContext', exportName: 'activeProjectSystemLinks' },
  },
]

export const SYSTEM_OBJECT_DEFINITION: ObjectDefinition = {
  key: 'system',
  label: 'System',
  pluralLabel: 'Systems',
  identityField: 'sid',
  source: systemInventorySource,
  fields: systemFields,
  sections: [
    { id: 'identity', label: 'Identity', source: systemInventorySource },
    { id: 'inventory', label: 'Inventory', source: systemInventorySource },
    { id: 'hosting', label: 'Hosting', source: hostingContextSource },
    { id: 'configuration', label: 'Configuration', source: { domain: 'ApplicationConfiguration', exportName: 'APPLICATION_CONFIGURATION_FIELDS' } },
  ],
  tabs: [
    { id: 'tenant', label: 'Tenant', source: systemInventorySource },
    { id: 'infrastructure', label: 'Platform', source: hostingContextSource },
    { id: 'versionUpdate', label: 'Version update', source: systemInventorySource },
    { id: 'usage', label: 'Usage', source: systemInventorySource },
    { id: 'configurationHistory', label: 'Configuration history', source: { domain: 'ApplicationConfiguration', exportName: 'configurationHistory' } },
    { id: 'documents', label: 'Documents', source: { domain: 'DocumentCollection' } },
  ],
  relationships: [
    { relationship: 'composes', domain: 'SystemInventory', exportName: 'getSystemInventoryMetadata' },
    { relationship: 'composes', domain: 'HostingContext', exportName: 'DEFAULT_HOSTING_CONTEXT' },
    { relationship: 'composes', domain: 'ApplicationConfiguration', exportName: 'APPLICATION_CONFIGURATION_FIELDS' },
    { relationship: 'references', domain: 'AllocationContext', exportName: 'activeProjectSystemLinks' },
    { relationship: 'hosts', domain: 'TenantRequirement', description: 'Tenant creation remains System Add Tenant flow using tenant requirement id.' },
    { relationship: 'composes', domain: 'DocumentCollection' },
  ],
}

const tenantConfigurationSource: ObjectMetadataSourceRef = {
  domain: 'ApplicationConfiguration',
  exportName: 'TENANT_CONFIGURATION_FIELDS',
}

const tenantFields: ObjectFieldDefinition[] = [
  {
    key: 'tid',
    label: 'TID',
    type: 'readonly',
    section: 'identity',
    editable: false,
    source: { domain: 'TenantRequirement', exportName: 'createTenantRequirementId', fieldKey: 'tid' },
  },
  {
    key: 'tenantName',
    label: 'Tenant Name',
    type: 'text',
    section: 'identity',
    editable: true,
    source: { domain: 'TenantRequirement', exportName: 'tenantRequirementReadModel', fieldKey: 'tenantName' },
  },
  {
    key: 'tenantType',
    label: 'Tenant Type',
    type: 'readonly',
    section: 'identity',
    editable: false,
    source: { domain: 'TenantRequirement', exportName: 'tenantRequirementReadModel', fieldKey: 'tenantType' },
  },
  {
    key: 'systemId',
    label: 'System ID/reference',
    type: 'reference',
    section: 'hosting',
    editable: false,
    source: { domain: 'HostingContext', exportName: 'hostingSnapshotFromTenant', fieldKey: 'systemId' },
  },
  {
    key: 'hostingSnapshot',
    label: 'Hosting Snapshot',
    type: 'collection',
    section: 'hosting',
    editable: false,
    source: { domain: 'HostingContext', exportName: 'hostingSnapshotFromTenant' },
    readModelSource: { domain: 'HostingContext', exportName: 'tenantHostingPatchFromSystem' },
  },
  {
    key: 'configuration',
    label: 'Application Configuration',
    type: 'collection',
    tab: 'configuration',
    editable: true,
    source: tenantConfigurationSource,
    validationSource: { domain: 'ApplicationConfiguration', exportName: 'validateApplicationConfiguration' },
  },
  {
    key: 'productType',
    label: 'Product',
    type: 'picklist',
    section: 'configuration',
    editable: true,
    source: { ...tenantConfigurationSource, fieldKey: 'productType' },
    picklistSource: { domain: 'ApplicationConfiguration', exportName: 'TENANT_CONFIGURATION_FIELDS', fieldKey: 'productType' },
  },
  {
    key: 'warranties',
    label: 'Warranty records',
    type: 'collection',
    tab: 'warranty',
    editable: true,
    source: { domain: 'WarrantyCollection', exportName: 'computeTenantWarranties' },
    validationSource: { domain: 'WarrantyCollection', exportName: 'canManageWarrantyCollection' },
  },
  {
    key: 'warrantyStatus',
    label: 'Warranty Status',
    type: 'readonly',
    section: 'warranty',
    editable: false,
    source: { domain: 'WarrantyCollection', exportName: 'warrantyStatusForRecord', fieldKey: 'warrantyStatus' },
  },
  {
    key: 'engagementCircle',
    label: 'Engagement Circle',
    type: 'collection',
    tab: 'engagementCircles',
    editable: true,
    source: { domain: 'EngagementCircle', exportName: 'normalizeTenantEngagementCircle' },
    readModelSource: { domain: 'EngagementCircle', exportName: 'tenantEngagementCircleView' },
  },
  {
    key: 'documents',
    label: 'Documents',
    type: 'collection',
    tab: 'documents',
    editable: true,
    source: { domain: 'DocumentCollection' },
  },
]

export const TENANT_OBJECT_DEFINITION: ObjectDefinition = {
  key: 'tenant',
  label: 'Tenant',
  pluralLabel: 'Tenants',
  identityField: 'tid',
  source: { domain: 'TenantRequirement', exportName: 'tenantRequirementReadModel' },
  fields: tenantFields,
  sections: [
    { id: 'identity', label: 'Identity', source: { domain: 'TenantRequirement', exportName: 'tenantRequirementReadModel' } },
    { id: 'hosting', label: 'Hosting', source: { domain: 'HostingContext', exportName: 'hostingSnapshotFromTenant' } },
    { id: 'configuration', label: 'Configuration', source: tenantConfigurationSource },
    { id: 'warranty', label: 'Warranty', source: { domain: 'WarrantyCollection', exportName: 'computeTenantWarranties' } },
  ],
  tabs: [
    { id: 'configuration', label: 'Configuration', source: tenantConfigurationSource },
    { id: 'hosting', label: 'Hosting', source: { domain: 'HostingContext', exportName: 'hostingSnapshotFromTenant' } },
    { id: 'warranty', label: 'Warranty', source: { domain: 'WarrantyCollection', exportName: 'computeTenantWarranties' } },
    { id: 'engagementCircles', label: 'Engagement Circle', source: { domain: 'EngagementCircle', exportName: 'tenantEngagementCircleView' } },
    { id: 'documents', label: 'Documents', source: { domain: 'DocumentCollection' } },
  ],
  relationships: [
    { relationship: 'references', domain: 'ProjectLifecycle', exportName: 'linkedTenantsForProject' },
    { relationship: 'references', domain: 'SystemInventory', exportName: 'systemReadModel' },
    { relationship: 'composes', domain: 'HostingContext', exportName: 'hostingSnapshotFromTenant' },
    { relationship: 'composes', domain: 'ApplicationConfiguration', exportName: 'TENANT_CONFIGURATION_FIELDS' },
    { relationship: 'composes', domain: 'WarrantyCollection', exportName: 'computeTenantWarranties' },
    { relationship: 'composes', domain: 'EngagementCircle', exportName: 'tenantEngagementCircleView' },
    { relationship: 'composes', domain: 'DocumentCollection' },
  ],
}

export const OBJECT_REGISTRY_ENTRIES: ObjectRegistryEntry[] = [
  OPPORTUNITY_OBJECT_DEFINITION,
  PROJECT_OBJECT_DEFINITION,
  SYSTEM_OBJECT_DEFINITION,
  TENANT_OBJECT_DEFINITION,
]
