export {
  AWS_CSP_OPTIONS,
  AWS_GOV_REGIONS,
  AWS_REGIONS,
  AZURE_CSP_OPTIONS,
  AZURE_GOV_REGIONS,
  AZURE_REGIONS,
  CLOUD_PLATFORM_OPTIONS,
  CUSTOMER_DATACENTER_CSP_OPTIONS,
  HOSTING_OPTIONS,
  PRODUCT_OPTIONS,
  cloudPlatformOptionsForHosting,
  cloudRegionOptionsForCloudPlatform,
  cspOptionsForCloudPlatform,
  requiresCloudRegion,
} from '@/domain/hosting-context'
