import type { DashboardColumn } from '@/components/dashboard/DataDashboard'
import type { Tenant } from '@/data/seed.types'

export const tenantListColumns: DashboardColumn<Tenant>[] = [
{ id: 'tid', label: 'TID#', getValue: (r) => r.tid },
{ id: 'sid', label: 'SID#', getValue: (r) => r.systemId },
{ id: 'pocDeliveryPid', label: 'POC/Delivery PID#', getValue: () => '' },
{ id: 'projectType', label: 'Project Type', getValue: () => '' },
{ id: 'renewalPid', label: 'Renewal PID#', getValue: () => '' },
{
id: 'tenantStatus',
label: 'Tenant Status',
getValue: (r) => r.operationalStatus,
editable: true,
editKey: 'operationalStatus',
},
{ id: 'owner', label: 'Owner', getValue: () => '' },
{ id: 'region', label: 'Region', getValue: (r) => r.timeGroup },
{ id: 'projectName', label: 'Project Name', getValue: () => '' },
{
id: 'country',
label: 'Country',
getValue: (r) => r.country,
editable: true,
editKey: 'country',
},
{ id: 'state', label: 'State', getValue: () => '' },
{ id: 'endUser', label: 'End User', getValue: (r) => r.accountName },
{ id: 'tenant', label: 'Tenant', getValue: (r) => r.accountName },
{ id: 'tenantUrl', label: 'Tenant URL (text)', getValue: () => '' },
{ id: 'modules', label: 'Modules', getValue: () => '' },
{ id: 'cloudRegion', label: 'Cloud Region', getValue: () => '' },
{ id: 'hosting', label: 'Hosting', getValue: () => '' },
{ id: 'cloudEnvironment', label: 'Cloud Environment', getValue: () => '' },
{ id: 'csp', label: 'CSP', getValue: () => '' },
{ id: 'saasRegion', label: 'SaaS Region', getValue: () => '' },
{
id: 'product',
label: 'Product',
getValue: (r) => r.productType,
editable: true,
editKey: 'productType',
},
{ id: 'aiFeatures', label: 'AI Features', getValue: () => '' },
{ id: 'additionalFeatures', label: 'Additional Features', getValue: () => '' },
{ id: 'brand', label: 'Brand', getValue: () => '' },
{ id: 'licenses', label: 'No. of Licenses (Concurrent Login)', getValue: () => '' },
{ id: 'users', label: 'No. of Users (Named)', getValue: () => '' },
{ id: 'searches', label: 'Searches - Concurrent', getValue: () => '' },
{ id: 'analyses', label: 'Analyses - Concurrent', getValue: () => '' },
{ id: 'currentVersion', label: 'Current Version', getValue: () => '' },
{ id: 'lastVersionUpdate', label: 'Last Version Update', getValue: () => '' },
{
id: 'warrantyStatus',
label: 'Warranty Status',
getValue: (r) => r.warrantyStatus,
editable: true,
editKey: 'warrantyStatus',
},
{
id: 'pocStartDate',
label: 'POC Start Date',
getValue: (r) => r.pocStartDate ?? '',
editable: true,
editKey: 'pocStartDate',
},
{
id: 'pocEndDate',
label: 'POC End Date',
getValue: (r) => r.pocEndDate ?? '',
editable: true,
editKey: 'pocEndDate',
},
{ id: 'initialWarrantyStartDate', label: 'Initial Warranty Start Date', getValue: () => '' },
{ id: 'currentWarrantyStartDate', label: 'Current Warranty Start Date', getValue: () => '' },
{
id: 'warrantyEndDate',
label: 'Warranty End Date',
getValue: (r) => r.warrantyEndDate ?? '',
editable: true,
editKey: 'warrantyEndDate',
},
{ id: 'daysBeforeExpiration', label: 'Days Before Exp.', getValue: () => '' },
{ id: 'monthLeft', label: 'Month Left', getValue: () => '' },
{ id: 'yearsLeft', label: 'Years Left', getValue: () => '' },
{ id: 'tenantAlerts', label: 'Tenant Alerts', getValue: () => '' },
{ id: 'deliveryDate', label: 'Delivery Date', getValue: () => '' },
{ id: 'projectStatus', label: 'Project Status', getValue: () => '' },
{ id: 'customer', label: 'Customer', getValue: () => '' },
]